server:
  port: 8082
  servlet:
    context-path: /rest

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,env,logfile,loggers

springdoc:
  api-docs:
    path: /api-docs

logging:
  file:
    name: logs/protocol-validator.log

spring:
  application:
    name: HealthTech Protocol Engine
